### ISSUE TITLE
Issue uploading a WAV file

### ISSUE THREAD

**Issue by apuder** [lkesteloot/trs80-cassette-reader-js#5]
I tried to upload the 500 Baud version of pski's BREAKDOWN: https://pski.net/breakdown-a-new-trs-80-game/
The progress bar shows 100% but then it does not move to the next screen. I am using the hosted version of your app.
BTW: very nice project!

**Comment by lkesteloot** [comment]
Fixed! There were several problems, but mostly the WAV files used 8-bit audio, which I wasn't handling. Thank you!

(Changes 98e3f51, 6dc8a18, and 5f1791d were for this issue.)
